# Generated by Django 4.2.29 on 2026-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kifu',
            name='highlight_move',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
