# Generated by Django 4.2.3 on 2026-06-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kifu_app', '0002_kifu_highlight_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kifu',
            name='event_name',
        ),
    ]
