# Generated by Django 4.2.3 on 2026-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifu_app', '0003_remove_kifu_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kifu',
            name='black_rank',
            field=models.CharField(blank=True, choices=[('beginner', '初心者'), ('kyu', '級位者'), ('dan', '段位者'), ('pro', 'プロ')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kifu',
            name='white_rank',
            field=models.CharField(blank=True, choices=[('beginner', '初心者'), ('kyu', '級位者'), ('dan', '段位者'), ('pro', 'プロ')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('beginner', '初心者'), ('kyu', '級位者'), ('dan', '段位者'), ('pro', 'プロ')], default='', max_length=20),
        ),
    ]
